# -*- coding: utf-8 -*-
"""AmitfirstprogramonColab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_3fD5n5N-aKoNb7CbXcPt804mzYNL1UT
"""

import numpy as np
from sklearn.linear_model import LinearRegression
x = np.array([10,9,2,15,10,16,11,16]).reshape((-1,1))
y = np.array([95,80,10,50,45,98,38,93])

model = LinearRegression()
model.fit(x,y)
model = LinearRegression().fit(x,y)

r_sq = model.score(x,y)
print('coefficient of determincation:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)
new_model = LinearRegression().fit(x,y.reshape((-1,1)))
print('intercept:', new_model.intercept_)
print('slope:', new_model.coef_)
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
y_pred = model.intercept_ + model.coef_ *x
print('predicted response:', y_pred, sep='\n')
x_new = np.arange(5).reshape((-1,1))
print(x_new)

import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np
x = np.array([10,9,2,15,10,16,11,16]).reshape((-1,1))
y = np.array([95,80,10,50,45,98,38,93])
plt.scatter(x,y)

